version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5500:5432"
  node:
    restart: on-failure
    build:
      dockerfile: ./.config/node/Dockerfile.dev
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "8000:8000"