FROM alpine:node-lts as builder

WORKDIR /app
COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build:prod;

FROM alpine:node-lts

WORKDIR /app

COPY --from=builder /app/dist

EXPOSE 8000
CMD ["npm", "run", "start:dev"]